### PR TITLE
Migrate to TypeScript project

### PR DESCRIPTION
**Pull request by goccy**
Migrate to TypeScript project to resolve https://github.com/knocknote/pixi-after-effects/issues/13

# Changed Summary
- replace `*.js` to `*.ts`
- remove `Babel`
- migrate from `eslint` to `typescript-eslint`
- generate `.d.ts` files at `yarn build`
- introduce `prettier` and do format by it
- Of course, supports PIXI.js v4 and v5

### CODE REVIEW

**Comment by imbsky** [comment]
What's the blocker now?

**Comment by imbsky** [comment]
Maybe I can do this in a better way, so I can open a new PR if necessary.

**Comment by goccy** [comment]
@imbsky 
Thank you for the reaction !!
I will act again for the merge this PR .

**Comment by imbsky** [comment]
Great.

**Pull request merged**
